// One-time generator: stages the Wet Ink brand fonts as DURABLE, file-based
// assets the design-sync converter can ship. Writes:
//   .design-sync/fonts/<family>.woff2          (real font files, committed)
//   .design-sync/fonts/wetink-fonts.css        (@font-face, file url()) → cfg.extraFonts
//   .design-sync/fonts/wetink-font-vars.css    (:root --font-* vars)     → appended to cssEntry
//
// The converter's parseFontFaces requires url() to END in .woff2 (data-URIs are
// dropped), and cfg.extraFonts copies file-based woff2 into the bundle's fonts/.
// :root vars must live in the cssEntry (not @font-face), hence the split.
//
// Source = woff2 next/font/google downloaded into .next/static/media/ (main-latin
// "-s.p." subsets — basic latin + general punctuation). Bricolage Grotesque is a
// variable font (one file, weights 400–800); Space Mono needs 400 + 700.
// Re-run only if the fonts change (and .next exists).
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'

const MEDIA = '.next/static/media'
const OUT = '.design-sync/fonts'
const FONTS = [
  { src: '017d9bea37084d9b-s.p.41rroleoq1br7.woff2', out: 'bricolage-grotesque-variable.woff2', family: 'Bricolage Grotesque', weight: '400 800' },
  { src: 'dc0d9adbac686440-s.p.3cik_s2si-ft-.woff2', out: 'space-mono-400.woff2', family: 'Space Mono', weight: '400' },
  { src: '8d05cfa5faa8406c-s.p.1s123piy9_v1m.woff2', out: 'space-mono-700.woff2', family: 'Space Mono', weight: '700' },
]

mkdirSync(OUT, { recursive: true })
const faces = []
for (const f of FONTS) {
  const sp = join(MEDIA, f.src)
  if (!existsSync(sp)) {
    console.error(`✗ missing ${sp} — run \`pnpm build\` (or \`next dev\`) so next/font downloads it, then re-run.`)
    process.exit(1)
  }
  copyFileSync(sp, join(OUT, f.out))
  faces.push(`@font-face {
  font-family: "${f.family}";
  font-style: normal;
  font-weight: ${f.weight};
  font-display: swap;
  src: url("./${f.out}") format("woff2");
}`)
}

writeFileSync(join(OUT, 'wetink-fonts.css'),
  `/* Wet Ink brand @font-face — file-based for cfg.extraFonts (converter copies
   the woff2 into the bundle's fonts/ and ships these rules via fonts/fonts.css).
   GENERATED by .design-sync/gen-fonts.mjs. */\n${faces.join('\n')}\n`)

writeFileSync(join(OUT, 'wetink-font-vars.css'),
  `/* Wet Ink font CSS vars — appended to the cssEntry (gen-css.mjs) so the
   bundle resolves --font-sans/--font-mono to the brand families above.
   GENERATED by .design-sync/gen-fonts.mjs. */
:root {
  --font-bricolage-grotesque: "Bricolage Grotesque", system-ui, -apple-system, sans-serif;
  --font-space-mono: "Space Mono", ui-monospace, SFMono-Regular, Menlo, Monaco, monospace;
}\n`)

console.error(`✓ staged ${FONTS.length} woff2 + wetink-fonts.css + wetink-font-vars.css → ${OUT}/`)
