import { QrFrame } from "@/components/loyalty"

export function RewardCollectionQr({
  rewardId,
  rewardName,
}: {
  rewardId: string
  rewardName: string
}) {
  return (
    <div className="grid gap-3">
      <QrFrame label={`Merchant-scan QR for ${rewardName}`}>
        {/* eslint-disable-next-line @next/next/no-img-element -- same-origin reward QR is generated by a protected route */}
        <img
          src={`/reward/${rewardId}/qr.png`}
          alt={`QR code for collecting ${rewardName}`}
          className="aspect-square w-full object-contain"
        />
      </QrFrame>
      <div className="grid gap-1 rounded-xl bg-secondary px-3 py-2 text-center">
        <p className="text-sm font-bold text-foreground">
          Merchant scans this QR
        </p>
        <p className="text-xs leading-5 text-muted-foreground">
          Keep this screen open at the counter. The merchant scan marks the
          reward as collected from their device.
        </p>
      </div>
    </div>
  )
}
