"use client"

import Link from "next/link"
import { useEffect, useState } from "react"

import { QrFrame, StatusBanner } from "@/components/loyalty"
import { PresentCodeButton } from "@/components/customer/present-code-button"
import { Button } from "@/components/ui/button"
import {
  rewardQrCacheBustedSrc,
  rewardQrRefreshIntervalMs,
} from "@/lib/customer/reward-qr"
import { customerLoginHref } from "@/lib/navigation/safe-next-path"

/**
 * The customer-held reward QR. The encoded scan token has a 10-minute TTL
 * enforced at scan time, so a one-shot image could go stale while a customer
 * queues. This refreshes `qr.png` on an interval inside that TTL — each refresh
 * mints a fresh token (F11). A transient image failure shows a calm banner with
 * a retry instead of a broken-image glyph, and a skeleton holds the framed box
 * until the QR loads (F17).
 */
export function RewardCollectionQr({
  rewardId,
  rewardName,
}: {
  rewardId: string
  rewardName: string
}) {
  // `tick` cache-busts the src on each refresh; bumping it on retry also forces a
  // fresh fetch after an error.
  const [tick, setTick] = useState(0)
  const [loaded, setLoaded] = useState(false)
  const [errored, setErrored] = useState(false)
  // Consecutive image failures. An expired session mid-queue makes `qr.png`
  // 404 forever, so repeated failures surface a sign-in path instead of an
  // unwinnable retry loop (CUS-P3-10). A successful load resets it.
  const [failCount, setFailCount] = useState(0)

  useEffect(() => {
    const timer = setInterval(() => {
      setLoaded(false)
      setErrored(false)
      setTick((value) => value + 1)
    }, rewardQrRefreshIntervalMs())

    return () => clearInterval(timer)
  }, [])

  function retry() {
    setLoaded(false)
    setErrored(false)
    setTick((value) => value + 1)
  }

  const suggestSignIn = failCount >= 2

  return (
    <div className="grid gap-3">
      {errored ? (
        <StatusBanner title="We could not show your reward QR" tone="warning">
          <span className="grid gap-3">
            {/* Was "Pull down to refresh, or ask a team member." — an
                instruction that does nothing on a page with no pull-to-refresh,
                and different copy from the pass QR's identical failure. Both
                now say the same thing, and it is a thing the member can
                actually do (CUS 02#39). */}
            <span>Try again, or ask a team member to help.</span>
            {suggestSignIn ? (
              <span>
                Still not showing? You may be signed out on this phone —{" "}
                <Link
                  // The shared helper mirrors load-reward.ts's expired-session
                  // redirect target and routes `next` through safeNextPath.
                  href={customerLoginHref(`/reward/${rewardId}`)}
                  className="font-bold underline underline-offset-4"
                >
                  sign in with your number
                </Link>{" "}
                to bring it back.
              </span>
            ) : null}
            <Button
              type="button"
              size="lg"
              variant="secondary"
              className="w-full"
              onClick={retry}
            >
              Show a fresh code
            </Button>
          </span>
        </StatusBanner>
      ) : (
        <QrFrame label={`Merchant-scan QR for ${rewardName}`}>
          <div className="relative aspect-square w-full">
            {!loaded ? (
              <div
                aria-hidden="true"
                className="absolute inset-0 animate-pulse rounded-md bg-secondary motion-reduce:animate-none"
              />
            ) : null}
            {/* eslint-disable-next-line @next/next/no-img-element -- same-origin reward QR is generated by a protected route */}
            <img
              src={rewardQrCacheBustedSrc(rewardId, tick)}
              alt={`QR code for collecting ${rewardName}`}
              className="aspect-square w-full object-contain"
              onLoad={() => {
                setLoaded(true)
                setFailCount(0)
              }}
              onError={() => {
                setErrored(true)
                setFailCount((count) => count + 1)
              }}
            />
          </div>
        </QrFrame>
      )}
      {/* The caption explains a code that is not on screen while the failure
          banner is up — the pass QR replaces its whole panel on error and this
          one kept its caption (CUS 02#39). */}
      {errored ? null : (
        <p className="rounded-lg bg-secondary px-3 py-2 text-center text-sm font-bold text-foreground">
          Merchant scans this QR from their device
        </p>
      )}
      {/* Counter mode (02#33): the framed code is ~271px inside the receipt,
          which is fine held still and not fine across a bar at arm's length.
          Same refreshing source, full-bleed, nothing else on screen. */}
      {errored ? null : (
        <PresentCodeButton
          label="Show at the counter"
          title={rewardName}
          caption="Hold this up for the team to scan"
        >
          {/* eslint-disable-next-line @next/next/no-img-element -- same-origin reward QR from a protected route */}
          <img
            src={rewardQrCacheBustedSrc(rewardId, tick)}
            alt={`QR code for collecting ${rewardName}`}
            className="aspect-square w-full object-contain"
          />
        </PresentCodeButton>
      )}
      {/* The reward code is single-use with a ten-minute TTL, exactly like the
          pass code — but the refresh control only existed on the error path, so
          a member whose code was scanned or expired mid-queue could do nothing
          but wait for the interval. The pass QR has always offered this; the
          two failures are the same failure and now behave the same
          (CUS 02#39). */}
      {errored ? null : (
        <Button
          type="button"
          size="lg"
          variant="secondary"
          className="w-full"
          onClick={retry}
        >
          Show a fresh code
        </Button>
      )}
    </div>
  )
}
