import type { CustomerRewards } from "@/lib/customer/rewards"

/**
 * DB-free wallet fixtures for the /dev/home-harness rewards lane. Literal only
 * (no Date/now) so the harness is deterministic. Exercises every source: an
 * earned stamp reward, a birthday treat, a merchant-sent gift (each ready to
 * collect), an unlocked reward still needing setup, one on the way, plus
 * collected and expired history.
 */
export const HOME_HARNESS_REWARDS: CustomerRewards = {
  redeemable: [
    {
      rewardId: "rwd_earned",
      membershipId: "mem_1",
      businessName: "Old Crown Girton",
      rewardName: "Free flat white",
      rewardTerms: "Any size, on the house.",
      source: "stamp_cycle",
      collectionState: "ready",
      collectionReason: null,
      availableFrom: "2026-07-01T09:00:00.000Z",
      redeemableFrom: "2026-07-01",
      expiresAt: null,
      expiredAt: null,
      redeemedAt: null,
      createdAt: "2026-07-01T09:00:00.000Z",
    },
    {
      rewardId: "rwd_birthday",
      membershipId: "mem_1",
      businessName: "Old Crown Girton",
      rewardName: "Birthday fizz",
      rewardTerms: "A glass of prosecco during your birthday month.",
      source: "birthday_month",
      collectionState: "ready",
      collectionReason: null,
      availableFrom: "2026-07-01T09:00:00.000Z",
      redeemableFrom: "2026-07-01",
      expiresAt: "2026-07-31T22:30:00.000Z",
      expiredAt: null,
      redeemedAt: null,
      createdAt: "2026-07-01T09:00:00.000Z",
    },
    {
      rewardId: "rwd_direct",
      membershipId: "mem_2",
      businessName: "The Anchor",
      rewardName: "Manager's thank-you drink",
      rewardTerms: "A drink on us. Thanks for being a regular.",
      source: "merchant_direct",
      collectionState: "ready",
      collectionReason: null,
      availableFrom: "2026-07-01T09:00:00.000Z",
      redeemableFrom: "2026-07-01",
      expiresAt: "2026-08-15T12:00:00.000Z",
      expiredAt: null,
      redeemedAt: null,
      createdAt: "2026-07-01T09:00:00.000Z",
    },
  ],
  needsSetup: [
    {
      rewardId: "rwd_setup",
      membershipId: "mem_2",
      businessName: "The Anchor",
      rewardName: "A mystery reward",
      rewardTerms: "The venue team confirms the eligible item.",
      source: "stamp_cycle",
      collectionState: "blocked",
      collectionReason: "Complete your profile before redeeming",
      availableFrom: "2026-07-01T09:00:00.000Z",
      redeemableFrom: "2026-07-01",
      expiresAt: null,
      expiredAt: null,
      redeemedAt: null,
      createdAt: "2026-07-01T09:00:00.000Z",
    },
  ],
  upcoming: [
    {
      rewardId: "rwd_upcoming",
      membershipId: "mem_1",
      businessName: "Old Crown Girton",
      rewardName: "Free pastry",
      rewardTerms: "Pick from the counter selection.",
      source: "stamp_cycle",
      collectionState: "waiting",
      collectionReason: null,
      availableFrom: "2026-12-24T09:00:00.000Z",
      redeemableFrom: "2026-12-24",
      expiresAt: null,
      expiredAt: null,
      redeemedAt: null,
      createdAt: "2026-07-01T09:00:00.000Z",
    },
  ],
  redeemed: [
    {
      rewardId: "rwd_redeemed",
      membershipId: "mem_1",
      businessName: "Old Crown Girton",
      rewardName: "Free coffee",
      rewardTerms: "Any size, on the house.",
      source: "stamp_cycle",
      collectionState: "redeemed",
      collectionReason: null,
      availableFrom: "2026-06-01T09:00:00.000Z",
      redeemableFrom: "2026-06-01",
      expiresAt: null,
      expiredAt: null,
      redeemedAt: "2026-06-01T10:00:00.000Z",
      createdAt: "2026-05-25T09:00:00.000Z",
    },
  ],
  expired: [
    {
      rewardId: "rwd_expired",
      membershipId: "mem_1",
      businessName: "Old Crown Girton",
      rewardName: "Last year's fizz",
      rewardTerms: "A glass of prosecco during your birthday month.",
      source: "birthday_month",
      collectionState: "expired",
      collectionReason: "expired",
      availableFrom: "2025-07-01T09:00:00.000Z",
      redeemableFrom: "2025-07-01",
      expiresAt: "2025-07-31T22:30:00.000Z",
      expiredAt: "2025-07-31T22:30:00.000Z",
      redeemedAt: null,
      createdAt: "2025-07-01T09:00:00.000Z",
    },
  ],
}
