import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { spawnSync } from "node:child_process"

const projectDir = process.cwd()
const contract = JSON.parse(
  readFileSync(join(projectDir, "config/env-contract.json"), "utf8")
)

const command = process.argv[2] ?? "status"
const force = process.argv.includes("--force")

if (command === "status") {
  printStatus()
} else if (command === "write-local") {
  writeLocalEnv()
} else if (command === "pull-supabase") {
  pullSupabase()
} else if (command === "set-posthog") {
  setPostHog()
} else if (command === "set-resend") {
  setResend()
} else {
  console.error(
    "Usage: pnpm env:keys | pnpm env:write-local [--force] | pnpm env:pull-supabase <project-ref> | pnpm env:set-posthog | pnpm env:set-resend"
  )
  process.exit(1)
}

function printStatus() {
  console.log("Nabaperks key setup")
  console.log("")
  console.log("Local CLI availability:")
  console.log(
    `- supabase: ${available("supabase") ? "installed" : "use pnpm dlx supabase"}`
  )
  console.log(
    `- stripe: ${available("stripe") ? "installed" : "install with brew install stripe/stripe-cli/stripe"}`
  )
  console.log(
    `- vercel: ${available("vercel") ? "installed" : "use pnpm dlx vercel"}`
  )
  console.log(
    `- resend: ${available("resend") ? "installed" : "use pnpm dlx resend-cli"}`
  )
  console.log(
    `- posthog-cli: ${available("posthog-cli") ? "installed" : "use pnpm dlx @posthog/cli"}`
  )
  console.log("")
  console.log("Provider key sources:")
  console.log("")
  console.log("Supabase:")
  console.log("  pnpm dlx supabase projects list")
  console.log(
    "  pnpm dlx supabase projects api-keys --project-ref <ref> --output json"
  )
  console.log("  NEXT_PUBLIC_SUPABASE_URL=https://<ref>.supabase.co")
  console.log("  NEXT_PUBLIC_SUPABASE_ANON_KEY=<anon key from api-keys>")
  console.log("  SUPABASE_SERVICE_ROLE_KEY=<service_role key from api-keys>")
  console.log("")
  console.log("Stripe:")
  console.log("  brew install stripe/stripe-cli/stripe")
  console.log("  stripe login")
  console.log("  stripe listen --forward-to localhost:3000/api/stripe/webhook")
  console.log("  STRIPE_WEBHOOK_SECRET=<whsec_... printed by stripe listen>")
  console.log(
    "  STRIPE_GROWTH_PRICE_ID=<price_... from dashboard or stripe prices list>"
  )
  console.log(
    "  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY and STRIPE_SECRET_KEY come from Stripe API keys."
  )
  console.log("")
  console.log("Resend:")
  console.log("  pnpm dlx resend-cli login")
  console.log("  pnpm dlx resend-cli api-keys --help")
  console.log("  RESEND_API_KEY=<re_... created/listed in Resend>")
  console.log("")
  console.log("PostHog:")
  console.log("  pnpm dlx @posthog/cli login")
  console.log(
    "  NEXT_PUBLIC_POSTHOG_KEY=<project key from project settings/API>"
  )
  console.log("  NEXT_PUBLIC_POSTHOG_HOST=https://eu.i.posthog.com")
  console.log("")
  console.log("Vercel:")
  console.log("  pnpm dlx vercel link")
  console.log("  pnpm dlx vercel env pull .env.local")
  console.log("  pnpm dlx vercel env add <NAME> production")
  console.log("")
  console.log("After exporting values in your shell, write .env.local with:")
  console.log("  pnpm env:write-local")
  console.log("")
  console.log("To merge Supabase keys directly into .env.local:")
  console.log("  pnpm env:pull-supabase <project-ref>")
  console.log("")
  console.log("To merge a Resend key from your shell without printing it:")
  console.log("  RESEND_API_KEY=re_... pnpm env:set-resend")
  console.log("")
  console.log("To merge PostHog browser analytics values without printing them:")
  console.log(
    "  NEXT_PUBLIC_POSTHOG_KEY=phc_... NEXT_PUBLIC_POSTHOG_HOST=https://eu.i.posthog.com pnpm env:set-posthog"
  )
}

function writeLocalEnv() {
  const target = join(projectDir, ".env.local")

  if (existsSync(target) && !force) {
    console.error(
      ".env.local already exists. Re-run with --force to overwrite."
    )
    process.exit(1)
  }

  const missing = contract
    .filter((entry) => !entry.optional)
    .filter((entry) => !process.env[entry.name]?.trim())
    .map((entry) => entry.name)

  if (missing.length) {
    console.error("Missing required shell variables:")
    for (const name of missing) {
      console.error(`- ${name}`)
    }
    console.error("")
    console.error("Export them first, then run pnpm env:write-local again.")
    process.exit(1)
  }

  const lines = [
    "# Generated by pnpm env:write-local",
    "# Do not commit this file.",
    "",
  ]

  for (const entry of contract) {
    lines.push(`# ${entry.description}`)
    lines.push(`${entry.name}=${process.env[entry.name] ?? ""}`)
    lines.push("")
  }

  writeFileSync(target, `${lines.join("\n").trimEnd()}\n`, {
    mode: 0o600,
  })

  console.log("Wrote .env.local from current shell variables.")
  console.log("Run pnpm env:check to validate it.")
}

function pullSupabase() {
  const projectRef = process.argv[3]?.trim()

  if (!projectRef || projectRef.startsWith("--")) {
    console.error("Usage: pnpm env:pull-supabase <project-ref>")
    process.exit(1)
  }

  const result = spawnSync(
    "pnpm",
    [
      "dlx",
      "supabase",
      "projects",
      "api-keys",
      "--project-ref",
      projectRef,
      "--output",
      "json",
    ],
    {
      cwd: projectDir,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    }
  )

  if (result.status !== 0) {
    console.error("Unable to pull Supabase API keys.")
    if (result.stderr.trim()) {
      console.error(result.stderr.trim())
    }
    process.exit(result.status ?? 1)
  }

  const parsed = parseJsonFromOutput(result.stdout)
  const anonKey = findSupabaseKey(parsed, "anon")
  const serviceRoleKey = findSupabaseKey(parsed, "service_role")

  if (!anonKey || !serviceRoleKey) {
    console.error(
      "Supabase API key output did not include anon and service_role keys."
    )
    process.exit(1)
  }

  mergeLocalEnv({
    NEXT_PUBLIC_SUPABASE_URL: `https://${projectRef}.supabase.co`,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: anonKey,
    SUPABASE_SERVICE_ROLE_KEY: serviceRoleKey,
  })

  console.log("Merged Supabase values into .env.local:")
  console.log("- NEXT_PUBLIC_SUPABASE_URL")
  console.log("- NEXT_PUBLIC_SUPABASE_ANON_KEY")
  console.log("- SUPABASE_SERVICE_ROLE_KEY")
  console.log("Run pnpm env:check after the remaining provider values are set.")
}

function setResend() {
  const resendKey = process.env.RESEND_API_KEY?.trim()

  if (!resendKey) {
    console.error("Set RESEND_API_KEY in your shell first.")
    console.error("Example: RESEND_API_KEY=re_... pnpm env:set-resend")
    process.exit(1)
  }

  if (!resendKey.startsWith("re_")) {
    console.error("RESEND_API_KEY should start with re_.")
    process.exit(1)
  }

  mergeLocalEnv({ RESEND_API_KEY: resendKey })
  console.log("Merged RESEND_API_KEY into .env.local.")
  console.log("Run pnpm env:check to validate the full contract.")
}

function setPostHog() {
  const postHogKey =
    process.env.NEXT_PUBLIC_POSTHOG_KEY?.trim() ||
    process.env.POSTHOG_PROJECT_API_KEY?.trim()
  const postHogHost =
    process.env.NEXT_PUBLIC_POSTHOG_HOST?.trim() ||
    readPostHogCliHost() ||
    "https://eu.i.posthog.com"

  if (!postHogKey) {
    console.error("Set NEXT_PUBLIC_POSTHOG_KEY in your shell first.")
    console.error(
      "Example: NEXT_PUBLIC_POSTHOG_KEY=phc_... NEXT_PUBLIC_POSTHOG_HOST=https://eu.i.posthog.com pnpm env:set-posthog"
    )
    process.exit(1)
  }

  if (!postHogKey.startsWith("phc_")) {
    console.error("NEXT_PUBLIC_POSTHOG_KEY should be the public project key and start with phc_.")
    console.error("Do not use a personal API token that starts with phx_.")
    process.exit(1)
  }

  try {
    new URL(postHogHost)
  } catch {
    console.error("NEXT_PUBLIC_POSTHOG_HOST must be a valid URL.")
    process.exit(1)
  }

  mergeLocalEnv({
    NEXT_PUBLIC_POSTHOG_KEY: postHogKey,
    NEXT_PUBLIC_POSTHOG_HOST: normalizePostHogHost(postHogHost),
  })
  console.log("Merged PostHog browser analytics values into .env.local:")
  console.log("- NEXT_PUBLIC_POSTHOG_KEY")
  console.log("- NEXT_PUBLIC_POSTHOG_HOST")
  console.log("Run pnpm env:check to validate the full contract.")
}

function mergeLocalEnv(updates) {
  const target = join(projectDir, ".env.local")
  const existing = existsSync(target) ? parseEnvFile(target) : {}
  const merged = { ...existing, ...updates }
  const names = contract.map((entry) => entry.name)
  const extraNames = Object.keys(merged).filter((name) => !names.includes(name))
  const lines = [
    "# Generated by Nabaperks env helpers.",
    "# Do not commit this file.",
    "",
  ]

  for (const entry of contract) {
    lines.push(`# ${entry.description}`)
    lines.push(`${entry.name}=${merged[entry.name] ?? ""}`)
    lines.push("")
  }

  for (const name of extraNames.sort()) {
    lines.push(`${name}=${merged[name]}`)
  }

  writeFileSync(target, `${lines.join("\n").trimEnd()}\n`, { mode: 0o600 })
}

function readPostHogCliHost() {
  const path = join(process.env.HOME ?? "", ".posthog/credentials.json")

  if (!existsSync(path)) return undefined

  try {
    const parsed = JSON.parse(readFileSync(path, "utf8"))
    return typeof parsed.host === "string" ? parsed.host : undefined
  } catch {
    return undefined
  }
}

function normalizePostHogHost(host) {
  if (host === "https://eu.posthog.com") return "https://eu.i.posthog.com"
  if (host === "https://us.posthog.com" || host === "https://app.posthog.com") {
    return "https://us.i.posthog.com"
  }

  return host
}

function parseEnvFile(path) {
  const parsed = {}
  const content = readFileSync(path, "utf8")

  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim()

    if (!trimmed || trimmed.startsWith("#")) continue

    const equalsIndex = trimmed.indexOf("=")

    if (equalsIndex === -1) continue

    parsed[trimmed.slice(0, equalsIndex)] = trimmed.slice(equalsIndex + 1)
  }

  return parsed
}

function parseJsonFromOutput(output) {
  const start = output.indexOf("[")
  const objectStart = output.indexOf("{")
  const jsonStart =
    start === -1
      ? objectStart
      : objectStart === -1
        ? start
        : Math.min(start, objectStart)

  if (jsonStart === -1) {
    console.error("Supabase CLI returned no JSON output.")
    process.exit(1)
  }

  try {
    return JSON.parse(output.slice(jsonStart))
  } catch {
    console.error("Unable to parse Supabase CLI JSON output.")
    process.exit(1)
  }
}

function findSupabaseKey(value, keyName) {
  const candidates = Array.isArray(value) ? value : Object.values(value ?? {})

  for (const candidate of candidates) {
    if (!candidate || typeof candidate !== "object") continue

    const label = String(
      candidate.name ??
        candidate.key ??
        candidate.type ??
        candidate.prefix ??
        ""
    ).toLowerCase()

    if (!label.includes(keyName)) continue

    for (const field of ["api_key", "apiKey", "value", "secret", "key"]) {
      const maybeKey = candidate[field]

      if (typeof maybeKey === "string" && maybeKey.length > 20) {
        return maybeKey
      }
    }
  }

  return undefined
}

function available(binary) {
  const result = spawnSync("zsh", ["-lc", `command -v ${binary}`], {
    stdio: "ignore",
  })

  return result.status === 0
}
